security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager
                always_use_default_target_path: false
                default_target_path:            /messaging

            logout:       true
            anonymous:    true

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_NO_ACCESS }
        - { path: ^/profile/edit, role: ROLE_NO_ACCESS }
        - { path: ^/profile/change-password, role: ROLE_NO_ACCESS }
        - { path: ^/resetting, role: ROLE_NO_ACCESS }
        - { path: ^/messaging/sent, role: ROLE_NO_ACCESS }
        - { path: ^/messaging/search, role: ROLE_NO_ACCESS }
        - { path: ^/delete, role: ROLE_NO_ACCESS }
        - { path: ^/undelete, role: ROLE_NO_ACCESS }
